services:
  - type: web
    name: job-dashboard
    env: python
    buildCommand: |
      apt-get update
      apt-get install -y curl gnupg apt-transport-https
      curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -
      curl https://packages.microsoft.com/config/debian/12/prod.list > /etc/apt/sources.list.d/mssql-release.list
      apt-get update
      ACCEPT_EULA=Y apt-get install -y msodbcsql17 unixodbc-dev
      pip install -r requirements.txt
    startCommand: gunicorn app:app
